num1 = float(input("Um numero real: "))
num2 = float(input("Um numero real: "))
num3 = float(input("Um numero real: "))
num4 = float(input("Um numero real: "))
num5 = float(input("Um numero real: "))
num6 = float(input("Um numero real: "))
num7 = float(input("Um numero real: "))
num8 = float(input("Um numero real: "))
num9 = float(input("Um numero real: "))
num10 = float(input("Um numero real: "))
lista = [num1, num2, num3, num4, num5, num6, num7, num8, num9, num10]
print(list(reversed(lista)))